# Generated by Django 5.2.4 on 2025-08-05 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works_to_do', '0004_workstodo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50, verbose_name='Nombre de la tarea')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de finalización')),
                ('finished', models.BooleanField(default=False, verbose_name='Terminada')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=255, verbose_name='Requerimiento')),
                ('fk_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='work_plan.task', verbose_name='Tarea')),
            ],
            options={
                'db_table': 'task_requirements',
            },
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50, verbose_name='Nombre del plan de trabajo')),
                ('status', models.BooleanField(default=False)),
                ('fk_works_to_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works_to_do.workstodo', verbose_name='Solicitud de trabajo')),
            ],
            options={
                'db_table': 'work_plan',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='fk_work_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_plan.workplan', verbose_name='Plan de Trabajo'),
        ),
    ]
