# Generated by Django 5.2.4 on 2025-08-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
