# Generated by Django 5.2.4 on 2025-07-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log_History',
        ),
    ]
