# Generated by Django 5.2.4 on 2025-07-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('rif', models.CharField(max_length=20, verbose_name='RIF')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
