# Generated by Django 5.2.4 on 2025-07-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='company_photos/', verbose_name='Foto'),
        ),
    ]
