# Generated by Django 5.2.4 on 2025-07-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_photo'),
        ('work_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='work_types',
            field=models.ManyToManyField(to='work_type.worktype', verbose_name='Tipos de Trabajo'),
        ),
    ]
