# Generated by Django 5.2.4 on 2025-07-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_work_types'),
        ('work_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='work_types',
            field=models.ManyToManyField(to='work_type.worktype', verbose_name='Servicios'),
        ),
    ]
