# Generated by Django 5.2.4 on 2025-07-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Empleado'), (2, 'Cliente')], default=0),
        ),
    ]
