# Generated by Django 5.2.4 on 2025-08-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_company_alter_userprofile_role'),
        ('work_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_types',
            field=models.ManyToManyField(blank=True, related_name='workers', to='work_type.worktype'),
        ),
    ]
