# Generated by Django 5.2.4 on 2025-07-23 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_work_types'),
        ('work_type', '0001_initial'),
        ('works_to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstodo',
            name='fk_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='workstodo',
            name='fk_work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_type.worktype', verbose_name='Servicio'),
        ),
    ]
