# Generated by Django 5.2.4 on 2025-07-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_type', '0001_initial'),
        ('works_to_do', '0002_alter_workstodo_fk_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstodo',
            name='fk_work_type',
        ),
        migrations.AddField(
            model_name='workstodo',
            name='fk_work_type',
            field=models.ManyToManyField(to='work_type.worktype', verbose_name='Servicio'),
        ),
    ]
