# Generated by Django 5.2.4 on 2025-07-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works_to_do', '0003_remove_workstodo_fk_work_type_workstodo_fk_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstodo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Programado'), (1, 'En Proceso'), (2, 'Terminado')], default=0, verbose_name='Estado del Trabajo'),
        ),
    ]
