# Generated by Django 5.2.4 on 2025-08-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works_to_do', '0004_workstodo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstodo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Programado'), (2, 'En Proceso'), (3, 'Terminado')], default=0, verbose_name='Estado del Trabajo'),
        ),
    ]
